# Generated by Django 5.2.5 on 2025-08-20 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="date_of_birth",
            new_name="birth_date",
        ),
    ]
