# Generated by Django 5.2.5 on 2025-08-20 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_date_of_birth_customuser_birth_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="birth_date",
            new_name="date_of_birth",
        ),
    ]
